CLIENT_ID = "698293805596-lm99e4u6a7ri7f8b5m8q6e1666fhio30.apps.googleusercontent.com"
CLIENT_SECRET = "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"
GROQ_API_KEY = "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"
MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"
CONVERTAPI_SECRET = "bAucc4WimFZRfGCftYXyIy6HWE3TtHtX"
